# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
    paths:
      - '**.swift'    
  pull_request:
    branches: [ "main" ]
    paths:
      - '**.swift'

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and Test
      run: |
        xcodebuild clean build analyze test -scheme AccessibilityFocused -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11'
